export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const GET_CUSTOMER_BY_ID = 'GET_CUSTOMER_BY_ID';
export const UPDATE_CUSTOMERS = 'UPDATE_CUSTOMERS';
export const SELECT_CUSTOMER = 'SELECT_CUSTOMER'